services:
  vpn:
    image: dperson/openvpn-client:latest
    container_name: gasvision-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    security_opt:
      - label:disable
    volumes:
      - ./docker/openvpn:/vpn
    environment:
      TZ: Europe/Warsaw
      VPN_FILES: pfSenseAZSC-udp-1194-gasvision-config.ovpn
      DEFAULT_GATEWAY: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  nn-service:
    build: .
    container_name: gasvision-nn-service
    network_mode: "service:vpn"
    depends_on:
      - vpn
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./storage:/tmp/nn-service-media
      - ./models:/app/models
    restart: unless-stopped